# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermai < Formula
  desc "Turn any website into a structured JSON API for AI agents."
  homepage "https://hermai.ai"
  version "0.2.2"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.2/hermai_0.2.2_darwin_amd64.tar.gz"
      sha256 "676f0630b9638532cc931051c50047f75a2d215d46fe88041d59f8c55bf57803"

      define_method(:install) do
        bin.install "hermai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.2/hermai_0.2.2_darwin_arm64.tar.gz"
      sha256 "b1dfea6b916e2cdada42dbe47f91438d8e323500aa19f177a431f449af1e39b2"

      define_method(:install) do
        bin.install "hermai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.2/hermai_0.2.2_linux_amd64.tar.gz"
      sha256 "9dc6b70748127b9b7d7f71b830ddd78e54197985002dca0213e0078ca31f36ab"
      define_method(:install) do
        bin.install "hermai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.2/hermai_0.2.2_linux_arm64.tar.gz"
      sha256 "1e96430c0aac6cb13903a74e9635d091f16f323eeff88d6c5b932043eae34022"
      define_method(:install) do
        bin.install "hermai"
      end
    end
  end

  test do
    assert_match "hermai version", shell_output("#{bin}/hermai --version")
  end
end
