# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermai < Formula
  desc "Turn any website into a structured JSON API for AI agents."
  homepage "https://hermai.ai"
  version "0.2.4"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.4/hermai_0.2.4_darwin_amd64.tar.gz"
      sha256 "6b76a86dbdbd4b69bf8d0312abacb3365ee1fb1d779e5a0561d6a29dd16dfbe0"

      define_method(:install) do
        bin.install "hermai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.4/hermai_0.2.4_darwin_arm64.tar.gz"
      sha256 "d53296f243b77eabdac6d14ddfbadd9bf31ca5511292645adc000d780cc0ab21"

      define_method(:install) do
        bin.install "hermai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.4/hermai_0.2.4_linux_amd64.tar.gz"
      sha256 "fa3a3c4897d7ec266c208f2ebd98295dd3152f44a9b341f9fbb79445598883c7"
      define_method(:install) do
        bin.install "hermai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hermai-ai/hermai-cli/releases/download/v0.2.4/hermai_0.2.4_linux_arm64.tar.gz"
      sha256 "dc517a53bbb7164fec1b7735226bab44b70c4d708dc55936c854bfed3c13de31"
      define_method(:install) do
        bin.install "hermai"
      end
    end
  end

  test do
    assert_match "hermai version", shell_output("#{bin}/hermai --version")
  end
end
